[profile.default]
src = "src"
out = "out"
libs = ["lib"]
remappings = [
  "solady/=lib/solady/",
  "@openzeppelin/contracts/security/=lib/openzeppelin-contracts/contracts/utils/",
]

fs_permissions = [{ access = "read", path = "test/WebAuthnSol/fixtures" }]
